# Generated by Django 5.2 on 2025-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animalphoto", models.ImageField(upload_to="profiles/")),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=100)),
            ],
        ),
    ]
